services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./user_data:/freqtrade/user_data
    entrypoint: sleep
    command: infinity
    tty: true

  download-data:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade-download
    restart: "no"
    env_file:
      - ./.env
    volumes:
      - ./user_data:/freqtrade/user_data
    entrypoint: freqtrade
    command: [
      "download-data",
      "--exchange", "${DOWNLOAD_EXCHANGE:-binance}",
      "--days", "${DOWNLOAD_DAYS:-30}",
      "--timeframes", "1m", "5m",
      "--pairs", "BTC/USDT", "ETH/USDT"
    ]
