services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./user_data:/freqtrade/user_data
    entrypoint: sleep
    command: infinity
    tty: true
