[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
py_version = 311

[tool.ruff]
line-length = 100
select = [
  "E","F","I","UP","B","S","W","C90"
]
ignore = [
  "E501"  # handled by black
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]

